source 'http://rubygems.org'


ruby '2.3.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record
gem 'pg', '0.20.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby


# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# gem 'jquery-turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
#gem 'sdoc', '~> 0.4.0', group :doc
gem 'puma'
gem 'rails_emoji_picker'

group :development do
  gem 'spring'
  gem 'letter_opener'
  gem 'web-console', '~> 2.0'
  gem 'faker'
  gem 'pry-rails'
  gem 'bullet'
  gem 'rack-mini-profiler'
end

group :production, :staging do
  gem 'rails_12factor'
  gem 'unicorn'
  gem "barnes"
end

group :development, :test do
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'devise'
gem 'watu_table_builder', :require => 'table_builder'

gem 'omniauth-facebook'
gem 'omniauth-linkedin-oauth2'
gem 'omniauth-google-oauth2'

gem 'paperclip', '~> 5.0.0'
gem 'aws-sdk', '~> 2.3.0'
gem 'font-awesome-rails', '>= 4.7.0'
gem 'cancancan', '~> 1.10'
gem 'rails_admin', '~> 1.1.1'

# For dates
gem 'bootstrap-datepicker-rails'
# For datetimes
gem 'fullcalendar-rails'
gem 'momentjs-rails', '>= 2.8.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'

gem 'geocoder'
gem 'remotipart', '~> 1.2'
gem 'unread'
gem 'stripe'
gem 'httparty'
gem 'select2-rails'
gem 'material_icons'
gem 'route_translator'
gem 'airbrake', '~> 7.2'
gem 'acts_as_paranoid', '~> 0.5.0'
gem 'roo-xls'
gem 'roo'
gem 'trix'
gem 'will_paginate', '~> 3.1.1'
gem 'paperclip-compression'
gem 'fancybox2-rails'

gem 'griddler'
gem 'griddler-sendgrid'