# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_api_key: AIzaSyB4jmqyVpIrq8dmRYdw34AXaY2eQBlMjH8
  secret_key_base: 0c07d114b7cdf5e6b42be3a47f0baa23c57ce633526fb152d62be1d6d8e80effd4c7560851f00b5207b57055d47667ef6ba63c9655c615afedc47ae688cdc553
  facebook_app_id: 135649933884652
  facebook_app_secret: 2cd54186fa85afd2b4fcc6518d7d1832
  linkedin_app_id: 775eiu6koiwhgx
  linkedin_app_secret: MBKMLm5L1o9aXRYP
  google_app_id: 736505802481-k4bj654aca0ef2n5e68itsq5sirol7e7.apps.googleusercontent.com
  google_app_secret: 0IzK09Q2dcdXOO7TqaM-xaSV
  app_domain: condomediainc.local
  paperclip_url_secret: 996a85c9e1019bc67f1bd44a0e9172f38c04f64db2b2b0d5ff78160556843e2587ac6adc1516001ad17fdef8e8f455dd3dd745f2707682fde955e94c8e6fb9af
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  max_distance_from_building: 10
  application_fee_percent: 20
  max_coupons_on_basic_plan: 1
  max_coupons_on_premium_plan: 3
  max_coupons_on_pro_plan: 6
  max_buildings_on_basic_plan: 5
  max_buildings_on_premium_plan: 10
  max_buildings_on_pro_plan: 1000
  coupon_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  coupon_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  deal_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  deal_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  distance_units: km
  weeks_to_claim_vouchers: 4
  customer_support: '438 998 5221, weekdays 10am - 6pm EST'
  cm_support_mail: 'support@condo-media.com'
  google_api_key: ''

test:
  google_api_key: AIzaSyB4jmqyVpIrq8dmRYdw34AXaY2eQBlMjH8
  secret_key_base: a49799cc3b4e7033bfbe2f597b4643d304abf2c24675ca558d0f2cfc5baf9dd7c9a4ab98c25cc1d88540565f0a839ff960fb06b161c9a0f9766def9048d29665
  facebook_app_id: 135649933884652
  facebook_app_secret: 2cd54186fa85afd2b4fcc6518d7d1832
  linkedin_app_id: 775eiu6koiwhgx
  linkedin_app_secret: MBKMLm5L1o9aXRYP
  google_app_id: 736505802481-k4bj654aca0ef2n5e68itsq5sirol7e7.apps.googleusercontent.com
  google_app_secret: 0IzK09Q2dcdXOO7TqaM-xaSV
  app_domain: condomediainc.local
  paperclip_url_secret: 996a85c9e1019bc67f1bd44a0e9172f38c04f64db2b2b0d5ff78160556843e2587ac6adc1516001ad17fdef8e8f455dd3dd745f2707682fde955e94c8e6fb9af
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  max_distance_from_building: 10
  application_fee_percent: 20
  max_coupons_on_basic_plan: 1
  max_coupons_on_premium_plan: 3
  max_coupons_on_pro_plan: 6
  max_buildings_on_basic_plan: 5
  max_buildings_on_premium_plan: 10
  max_buildings_on_pro_plan: 1000
  coupon_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  coupon_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  deal_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  deal_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  distance_units: km
  weeks_to_claim_vouchers: 4
  customer_support: '438 998 5221, weekdays 10am - 6pm EST'
  cm_support_mail: 'support@condo-media.com'
  google_api_key: ''

staging:
  secret_key_base: a49799cc3b4e7033bfbe2f597b4643d304abf2c24675ca558d0f2cfc5baf9dd7c9a4ab98c25cc1d88540565f0a839ff960fb06b161c9a0f9766def9048d29665
  facebook_app_id: 135649933884652
  facebook_app_secret: 2cd54186fa85afd2b4fcc6518d7d1832
  linkedin_app_id: 775eiu6koiwhgx
  linkedin_app_secret: MBKMLm5L1o9aXRYP
  google_app_id: 736505802481-k4bj654aca0ef2n5e68itsq5sirol7e7.apps.googleusercontent.com
  google_app_secret: 0IzK09Q2dcdXOO7TqaM-xaSV
  app_domain: <%= ENV["APP_DOMAIN"] %>
  paperclip_url_secret: 996a85c9e1019bc67f1bd44a0e9172f38c04f64db2b2b0d5ff78160556843e2587ac6adc1516001ad17fdef8e8f455dd3dd745f2707682fde955e94c8e6fb9af
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  max_distance_from_building: 10
  application_fee_percent: 20
  max_coupons_on_basic_plan: 1
  max_coupons_on_premium_plan: 3
  max_coupons_on_pro_plan: 6
  max_buildings_on_basic_plan: 5
  max_buildings_on_premium_plan: 10
  max_buildings_on_pro_plan: 1000
  coupon_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  coupon_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  deal_highlight_prices_map: "{'7' => 5, '15' => 10, '30' => 20}"
  deal_top_prices_map: "{'7' => 10, '15' => 20, '30' => 30}"
  distance_units: km
  weeks_to_claim_vouchers: 4
  customer_support: '438 998 5221, weekdays 10am - 6pm EST'
  cm_support_mail: 'support@condo-media.com'
  google_api_key: <%= ENV["GOOGLE_APP_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  linkedin_app_id: <%= ENV["LINKEDIN_APP_ID"] %>
  linkedin_app_secret: <%= ENV["LINKEDIN_APP_SECRET"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV["GOOGLE_APP_SECRET"] %>
  app_domain: <%= ENV["APP_DOMAIN"] %>
  paperclip_url_secret: <%= ENV["PAPERCLIP_URL_SECRET"] %>
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  max_distance_from_building: <%= ENV["MAX_DISANCE_FROM_BUILDING"] %>
  application_fee_percent: <%= ENV["APPLICATION_FEE_PERCENT"] %>
  max_coupons_on_basic_plan: <%= ENV["MAX_COUPONS_ON_BASIC_PLAN"] %>
  max_coupons_on_premium_plan: <%= ENV["MAX_COUPONS_ON_PREMIUM_PLAN"] %>
  max_coupons_on_pro_plan: <%= ENV["MAX_COUPONS_ON_PRO_PLAN"] %>
  max_buildings_on_basic_plan: <%= ENV["MAX_BUILDINGS_ON_BASIC_PLAN"] %>
  max_buildings_on_premium_plan: <%= ENV["MAX_BUILDINGS_ON_PREMIUM_PLAN"] %>
  max_buildings_on_pro_plan: <%= ENV["MAX_BUILDINGS_ON_PRO_PLAN"] %>
  coupon_highlight_prices_map: <%= ENV["COUPON_HIGHLIGHT_PRICES_MAP"] %>
  coupon_top_prices_map: <%= ENV["COUPON_TOP_PRICES_MAP"] %>
  deal_highlight_prices_map: <%= ENV["DEAL_HIGHLIGHT_PRICES_MAP"] %>
  deal_top_prices_map: <%= ENV["DEAL_TOP_PRICES_MAP"] %>
  distance_units: <%= ENV["DISTANCE_UNITS"] %>
  weeks_to_claim_vouchers: <%= ENV["WEEKS_TO_CLAIM_VOUCHERS"] %>
  customer_support: <%= ENV["CUSTOMER_SUPPORT"] %>
  cm_support_mail: <%= ENV["CM_SUPPORT_MAIL"] %>
  google_api_key: <%= ENV["GOOGLE_APP_KEY"] %>
